//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int IdCalificacion { get; set; }
        public Nullable<int> IdEstudiante { get; set; }
        public Nullable<int> IdCriterio { get; set; }
        public Nullable<decimal> NotaBase { get; set; }
        public Nullable<decimal> NotaFinal { get; set; }
    
        public virtual Criterios Criterios { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
