//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacionAvanzada
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterios()
        {
            this.Calificaciones = new HashSet<Calificaciones>();
        }
    
        public int IdCriterio { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<int> IdProfesor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificaciones> Calificaciones { get; set; }
        public virtual Profesores Profesores { get; set; }
    }
}
